Repository fpt-blue-green/server, pull requests merged in 2024-08, with the labels that each got.

#1 [ADF-30] [BE] Tạo Project Structure
  AdFusionAPI/AdFusionAPI.csproj
  AdFusionAPI/Controllers/WeatherForecastController.cs
  AdFusionAPI/Program.cs
  AdFusionAPI/Properties/launchSettings.json
  AdFusionAPI/WeatherForecast.cs
  AdFusionAPI/appsettings.Development.json
  AdFusionAPI/appsettings.json
  AdFusion_BackEnd.sln
  BusinessObjects/BusinessObjects.csproj
  BusinessObjects/appsettings.json
  Repositories/Repositories.csproj
  Service/Domain/ConfigManager.cs
  Service/Service.csproj
Labels: resolved

#2 [ADF-40] [BE] Config API cho dự án
  AdFusionAPI/APIConfig/JwtConfiguration.cs
  AdFusionAPI/AdFusionAPI.csproj
  BusinessObjects/BusinessObjects.csproj
  Repositories/Repositories.csproj
  Service/Implement/SecurityService.cs
  Service/Interface/ISecurityService.cs
  Service/Resources/ConfigManager.cs
  Service/Service.csproj
Labels: resolved

#3 [ADF-41] [BE] Tạo phương thức ValidateToken và GenerateToken
  AdFusionAPI/APIConfig/DependencyInjection.cs
  AdFusionAPI/Program.cs
Labels: review

#5 [ADF-34] Tạo Model từ Database cho Back-end
  BusinessObjects/BusinessObjects.csproj
  BusinessObjects/DbContext/PostgresContext.cs
  BusinessObjects/Models/AdminAction.cs
  BusinessObjects/Models/AdsCampaign.cs
  BusinessObjects/Models/BannedUser.cs
  BusinessObjects/Models/Brand.cs
  BusinessObjects/Models/Campaign.cs
  BusinessObjects/Models/CampaignTag.cs
  BusinessObjects/Models/Channel.cs
  BusinessObjects/Models/Deal.cs
  BusinessObjects/Models/Feedback.cs
  BusinessObjects/Models/Image.cs
  BusinessObjects/Models/Influencer.cs
  BusinessObjects/Models/InfluencerJobHistory.cs
  BusinessObjects/Models/InfluencerTag.cs
  BusinessObjects/Models/Job.cs
  BusinessObjects/Models/Offer.cs
  BusinessObjects/Models/Package.cs
  BusinessObjects/Models/Payment.cs
  BusinessObjects/Models/SystemSetting.cs
  BusinessObjects/Models/Tag.cs
  BusinessObjects/Models/User.cs
  Repositories/Implement/InfluencerRepository.cs
  Repositories/Interface/IInfluencerRepository.cs
  Service/Implement/InfluencerService.cs
  Service/Interface/IInfluencerService.cs
Labels: resolved

#7 Hoang dev
  AdFusionAPI/APIConfig/DependencyInjection.cs
  AdFusionAPI/Controllers/SystemSettingController.cs
  AdFusionAPI/Controllers/WeatherForecastController.cs
  AdFusionAPI/Program.cs
  AdFusionAPI/WeatherForecast.cs
  BusinessObjects/BusinessObjects.csproj
  BusinessObjects/Enum/HttpStatusCode.cs
  BusinessObjects/Enum/SystemSettingDTO.cs
  BusinessObjects/ModelsDTO/ApiResponse.cs
  Repositories/Implement/SystemSettingRepository.cs
  Repositories/Interface/ISystemSettingRepository.cs
  Service/Implement/EmailService.cs
  Service/Implement/SystemSettingService.cs
  Service/Interface/IEmailService.cs
  Service/Interface/ISystemSettingService.cs
  Service/Resources/ConfigManager.cs
  Service/Resources/EmailTemplate.cs
Labels: resolved

#8 [ADF-52] [BE] API lấy thông tin người sử dụng ở TitkTok
  AdFusionAPI/Controllers/UtilityController.cs
  Service/Implement/UtilityService.cs
  Service/Interface/IUtilityService.cs
  Service/Service.csproj
Labels: resolved

#9 [ADF-56] [BE] API lấy thông tin video ở TitkTok
  AdFusionAPI/Controllers/UtilityController.cs
  Service/Implement/UtilityService.cs
  Service/Interface/IUtilityService.cs
Labels: resolved

#11 [ADF-43][BE] Hoàn thiện API trang Home
  AdFusionAPI/Controllers/HomeController.cs
  AdFusionAPI/appsettings.json
  BusinessObjects/DbContext/PostgresContext.cs
  BusinessObjects/Models/AdminAction.cs
  BusinessObjects/Models/AdsCampaign.cs
  BusinessObjects/Models/BannedUser.cs
  BusinessObjects/Models/Brand.cs
  BusinessObjects/Models/Campaign.cs
  BusinessObjects/Models/CampaignTag.cs
  BusinessObjects/Models/Channel.cs
  BusinessObjects/Models/Deal.cs
  BusinessObjects/Models/Feedback.cs
  BusinessObjects/Models/Image.cs
  BusinessObjects/Models/Influencer.cs
  BusinessObjects/Models/InfluencerJobHistory.cs
  BusinessObjects/Models/InfluencerTag.cs
  BusinessObjects/Models/Job.cs
  BusinessObjects/Models/Offer.cs
  BusinessObjects/Models/Package.cs
  BusinessObjects/Models/PostgresContext.cs
  BusinessObjects/Models/Tag.cs
  BusinessObjects/Models/User.cs
  Repositories/Helper/SingletonBase.cs
  Service/Implement/InfluencerService.cs
Labels: resolved

#13 [ADF-63] [BE] Tạo API login
  AdFusionAPI/APIConfig/DependencyInjection.cs
  AdFusionAPI/Controllers/AuthenController.cs
  BusinessObjects/BusinessObjects.csproj
  BusinessObjects/Enum/AuthenEnumContainer.cs
  BusinessObjects/ModelsDTO/AuthenDTO/ChangePassDTO.cs
  BusinessObjects/ModelsDTO/AuthenDTO/ForgotPasswordDTO.cs
  BusinessObjects/ModelsDTO/AuthenDTO/LoginDTO.cs
  BusinessObjects/ModelsDTO/AuthenDTO/RegisterDTO.cs
  BusinessObjects/ModelsDTO/UserDTO.cs
  Repositories/Implement/AuthenRepository.cs
  Repositories/Interface/IAuthenRepository.cs
  Service/Implement/AuthenService.cs
  Service/Interface/IAuthenService.cs
Labels: resolved

#14 [ADF-64] [BE] Tạo API Register
  AdFusionAPI/APIConfig/DependencyInjection.cs
  AdFusionAPI/Controllers/AuthenController.cs
  BusinessObjects/ModelsDTO/AuthenDTO/RegisterDTO.cs
  BusinessObjects/ModelsDTO/UserDTO.cs
  Service/Implement/AuthenService.cs
  Service/Interface/IAuthenService.cs
  Service/Resources/ConfigManager.cs
Labels: resolved

#17 [ADF-60] Complete Logic
  AdFusionAPI/Controllers/UtilityController.cs
  Service/Implement/UtilityService.cs
  Service/Interface/IUtilityService.cs
Labels: review

#18 [ADF-51] [BE] API để lấy thông tin người sử dụng ở Instagram
  AdFusionAPI/Controllers/UtilityController.cs
  Service/Implement/UtilityService.cs
  Service/Interface/IUtilityService.cs
Labels: review, resolved

#19 [ADF-66][ADF-67]response influencerDto and setup automapper
  AdFusionAPI/Controllers/HomeController.cs
  AdFusionAPI/Program.cs
  BusinessObjects/Models/Channel.cs
  BusinessObjects/Models/Image.cs
  BusinessObjects/Models/PostgresContext.cs
  BusinessObjects/ModelsDTO/InfluencerDTO/ChannelDTO.cs
  BusinessObjects/ModelsDTO/InfluencerDTO/ImagesDTO.cs
  BusinessObjects/ModelsDTO/InfluencerDTO/InfluencerDTO.cs
  BusinessObjects/ModelsDTO/InfluencerDTO/InfluencerTagDTO.cs
  BusinessObjects/ModelsDTO/InfluencerDTO/PackageDTO.cs
  Repositories/Helper/AutoMapperProfile.cs
  Repositories/Implement/InfluencerRepository.cs
  Repositories/Repositories.csproj
  Service/Implement/InfluencerService.cs
Labels: resolved

#29 [ADF-65][ADF-44] update logic code
  AdFusionAPI/AdFusionAPI.csproj
  AdFusionAPI/Controllers/AuthController.cs
  AdFusionAPI/Controllers/InfluencersController.cs
  AdFusionAPI/Controllers/UploadImageController.cs
  AdFusionAPI/Controllers/UtilityController.cs
  AdFusionAPI/Program.cs
  AdFusionAPI/appsettings.json
  BusinessObjects/BusinessObjects.csproj
  BusinessObjects/DTOs/InfluencerDTOs/InfluencerDTO.cs
  BusinessObjects/DTOs/InfluencerDTOs/InfluencerRequestDTO.cs
  BusinessObjects/DTOs/InfluencerDTOs/TagRequestDTO.cs
  Repositories/Implement/FeedBackRepository.cs
  Repositories/Implement/InfluencerRepository.cs
  Repositories/Implement/TagRepository.cs
  Repositories/Interface/IFeedBackRepository.cs
  Repositories/Interface/IInfluencerRepository.cs
  Repositories/Interface/ITagRepository.cs
  Repositories/Repositories.csproj
  Service/Helper/AutoMapperProfile.cs
  Service/Implement/CloudinaryStorageService.cs
  Service/Implement/InfluencerService.cs
  Service/Interface/ICloudinaryStorageService.cs
  Service/Interface/IInfluencerService.cs
  Service/Service.csproj
Labels: resolved

#30 [ADF-65] update logic Upload image
  AdFusionAPI/APIConfig/DependencyInjection.cs
  AdFusionAPI/Controllers/UploadImageController.cs
  Service/Implement/CloudinaryStorageService.cs
Labels: resolved

#36 [ADF-94][ADF-97] update code
  AdFusionAPI/Controllers/InfluencersController.cs
  AdFusionAPI/Controllers/UserController.cs
  BusinessObjects/DTOs/InfluencerDTOs/InfluencerDTO.cs
  BusinessObjects/DTOs/InfluencerDTOs/InfluencerRequestDTO.cs
  BusinessObjects/DTOs/UserDTOs/UserTokenDTO.cs
  Repositories/Implement/InfluencerRepository.cs
  Repositories/Interface/IInfluencerRepository.cs
  Service/Helper/AutoMapperProfile.cs
  Service/Implement/AuthService.cs
  Service/Implement/InfluencerService.cs
  Service/Implement/UserService.cs
  Service/Interface/IAuthService.cs
  Service/Interface/IInfluencerService.cs
  Service/Interface/IUserService.cs
  Service/Resources/ConfigManager.cs
Labels: review
